---
- name: Create keys directory
  file:
    path: "~{{ username }}/.local/share/io.parity.ethereum/keys/{{ genesis_network_name }}"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Config mining key file
  copy:
    src: "./tmp/{{ timestamp }}/{{ name }}.json"
    dest: "{{ home }}/.local/share/io.parity.ethereum/keys/{{ genesis_network_name }}/peer.key"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Fetch core count
  shell: "cat /proc/cpuinfo | grep processor | wc -l"
  register: core_count

- name: Fetch address from key file
  shell: "grep -oP '(?<=\"address\":\")[^\"]*' {{ home }}/.local/share/io.parity.ethereum/keys/{{ genesis_network_name }}/peer.key"
  register: account

- name: Create logs directory
  file:
    path: "~{{ username }}/logs"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create an empty bootnodes.txt
  copy:
    content: ""
    dest: "~{{ username }}/bootnodes.txt"
    force: no
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0644

- name: Copy spec.json
  copy:
    src: "./tmp/{{ timestamp }}/spec.json"
    dest: ~{{ username }}/spec.json
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy node.toml
  template:
    src: "node.j2"
    dest: ~{{ username }}/node.toml
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Save passphrase to file
  lineinfile:
    path: "~{{ username }}/node.pwd"
    line: "{{ name }}"
    create: yes